### ISSUE TITLE
Simple Voice Chat  Pull Requests is open and wait of changes of many thinks. !!!

### ISSUE THREAD

**Issue by Mike74846** [ly-schneider/HeatCalculator#1]
Hi,
you have a Pull Requests make for Simple Voice Chat with Display Nametags. The Problem is henklemax have many thinks what not so good was. I hope you change this. I love the idear but then you not on your Pull requests. The Changes make will henklemax close your Pull requests. But I love your Idear. I hope you see this.

**Comment by Mike74846** [comment]
Your Pull Requests was close. It was sad. I have love the idear but you have no changes make for all versions.

**Comment by ly-schneider** [comment]
Hey Mike, if you are still interested I made a fork with a release for the change: [https://github.com/ly-schneider/simple-voice-chat/releases/tag/1.21.1-release](https://github.com/ly-schneider/simple-voice-chat/releases/tag/1.21.1-release). I didn't work on the PR anymore because I would had to update every current supported MC version and due to personal time issues I didn't do it.
